name: Run tests on package

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Install Dependencies
        run: mvn clean install -Dgpg.skip=true
      - name: Test with Maven
        run: mvn test -Dgpg.skip=true
