name: Run tests on package

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8', '11', '21']
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          overwrite-settings: true
      - name: Install Dependencies
        run: mvn clean install
      - name: Test with Maven
        run: mvn test
